version: "3.9"

services:
  db:
    image: mysql:8
    container_name: bank_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:bankdb}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  bankserver-app:
    build: .
    container_name: bankserver-app
    depends_on:
      - db
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:root}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:root}

volumes:
  mysql_data:
