version: "3.9"
services:
  mysql-bank:
    image: mysql:8.0
    container_name: mysql-bank
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bankdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  bankserver-app:
    build: .
    container_name: bankserver-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-bank:3306/bankdb?useSSL=false&serverTimezone=UTC
    depends_on:
      - mysql-bank

volumes:
  db_data:
